from torchaudio.prototype.ffmpeg.io import SourceAudioStream, SourceVideoStream


# Ref: https://ottverse.com/free-hls-m3u8-test-urls/
CONFIGS = [
    (
        "https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8",
        [
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=29.97002997002997,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=0,
                sample_rate=44100.0,
                num_channels=2,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=29.97002997002997,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=0,
                sample_rate=44100.0,
                num_channels=2,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=29.97002997002997,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=0,
                sample_rate=44100.0,
                num_channels=2,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=29.97002997002997,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=0,
                sample_rate=44100.0,
                num_channels=2,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=0,
                sample_rate=44100.0,
                num_channels=2,
            ),
        ],
    ),
    (
        "http://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_stereo_subs.m3u8",
        [
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=128000,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=132446,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
        ],
    ),
    (
        "http://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multichannel_subs.m3u8",
        [
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=192000,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="ac3",
                codec_long_name="ATSC A/52A (AC-3)",
                format="fltp",
                bit_rate=384000,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=128000,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=132446,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
        ],
    ),
    (
        "http://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multi_language_subs.m3u8",
        [
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=192000,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=192000,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=192000,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="ac3",
                codec_long_name="ATSC A/52A (AC-3)",
                format="fltp",
                bit_rate=384000,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="ac3",
                codec_long_name="ATSC A/52A (AC-3)",
                format="fltp",
                bit_rate=384000,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="ac3",
                codec_long_name="ATSC A/52A (AC-3)",
                format="fltp",
                bit_rate=384000,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=128000,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=128000,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="eac3",
                codec_long_name="ATSC A/52B (AC-3, E-AC-3)",
                format="fltp",
                bit_rate=128000,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=132446,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=132634,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=132634,
                sample_rate=48000.0,
                num_channels=2,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=768,
                height=432,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=480,
                height=270,
                frame_rate=25.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=416,
                height=234,
                frame_rate=4.0,
            ),
        ],
    ),
    (
        "http://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl)",
        [
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=386692,
                sample_rate=48000.0,
                num_channels=6,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=640,
                height=360,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=960,
                height=540,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1280,
                height=720,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=1920,
                height=1080,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=2560,
                height=1440,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=2560,
                height=1440,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=2560,
                height=1440,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=3840,
                height=2160,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=3840,
                height=2160,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=3840,
                height=2160,
                frame_rate=24.0,
            ),
            SourceVideoStream(
                media_type="video",
                codec="h264",
                codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                format="yuv420p",
                bit_rate=0,
                width=4096,
                height=2304,
                frame_rate=24.0,
            ),
            SourceAudioStream(
                media_type="audio",
                codec="aac",
                codec_long_name="AAC (Advanced Audio Coding)",
                format="fltp",
                bit_rate=0,
                sample_rate=48000.0,
                num_channels=6,
            ),
        ],
    ),
]
