url: http://pytorch.org/audio
name: PyTorch Audio
description: 'Scientific Computing...'
latest_version: 1.0
baseurl:
relative_permalinks: false
timezone: America/Los_Angeles
sass:
    sass_dir: _sass # default
    style: compressed
safe: true
highlighter: rouge
markdown: kramdown
future: true
include:
    - _images
    - _downloads
    - _static
    - _modules
    - _sources
    - _tts
    - _wav2vec2
    - _*.html
exclude:
    - node_modules
    - README.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json

plugins:
  - jekyll-feed
