name: ðŸ› Bug Report
description: Create a report to help us reproduce and fix the bug

body:
- type: markdown
  attributes:
    value: >
      <strong>PLEASE NOTE THAT THE TORCHAUDIO REPOSITORY IS NO LONGER ACTIVELY MONITORED.</strong> You will not likely get a response. For open discussions, visit https://discuss.pytorch.org/.
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/pytorch/audio/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: ðŸ› Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we hope to get the same result as you did: avoid any external data, and include the relevant imports, etc. For example:

      ```python
      # All necessary imports at the beginning
      import torch
      from torchaudio.transforms import Spectrogram, InverseSpectrogram

      # A succinct reproducing example trimmed down to the essential parts:
      theta = torch.linspace(0, 300 * 3.14, 8000)
      waveform = torch.sin(theta).unsqueeze(0)
      n_fft = 400
      center = False
      spec = Spectrogram(n_fft=n_fft, center=center, power=None, return_complex=True)(waveform)
      recon = InverseSpectrogram(n_fft=n_fft, center=center)(spec)  # Note: the bug is here, the window and center settings must satisfy NOLA check.
      print('recon:', recon.shape)
      ```

      If the code and or the traceback is too long, feel free to put it in a public gist and link it in the issue: https://gist.github.com.

      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.

      ```python
      Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ````
  validations:
    required: true
- type: textarea
  attributes:
    label: Versions
    description: |
      Please run the following and paste the output below.
      ```sh
      wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
      # For security purposes, please check the contents of collect_env.py before running it.
      python collect_env.py
      ```
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing ðŸŽ‰!
