channels:
  - defaults
dependencies:
  - flake8
  - pytest
  - pytest-cov
  - codecov
  - scipy >= 1.4.1
  - pip
  - pip:
    - PySoundFile
    - future
    - parameterized
    - dataclasses
    - expecttest
