channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - cpuonly
  - flake8
  - numpy
  - pytest
  - librosa
  - pip
  - pip:
    - kaldi-io
    - scipy
    - soundfile
