name: Integration Test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install -y -qq libavfilter-dev libavdevice-dev cmake ffmpeg
    - name: Install packages
      run: |
        python -m pip install --quiet --upgrade pip setuptools wheel
        python -m pip install --quiet numpy
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_CUDA=true
        unset CUDA_VERSION
        python -m pip install --quiet --pre torch torchcodec -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        python -m pip install --quiet pytest requests
        USE_CUDA=0 python -m pip install . -v --no-build-isolation
    - name: Run integration test
      run: |
        cd test && pytest integration_tests -v --use-tmp-hub-dir
